export const QUERY_KEYS = {
  GET_PRODUCT_DATA: 'GET_PRODUCT_DATA',
  GET_PRODUCT_BY_CATEGORY: 'GET_PRODUCT_BY_CATEGORY',
  GET_USER_DATA: 'GET_USER_DATA',
  GET_PROFILE: 'GET_PROFILE',
  GET_ORDER_BY_TABLE_ID: 'GET_ORDER_BY_TABLE_ID',
  GET_TABLES: 'GET_TABLES',
  GET_ORDER_ITEM_DATA: 'GET_ORDER_ITEM_DATA',
};
