export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const UPDATE_QUANTITY_CART_ITEM = 'UPDATE_QUANTITY_CART_ITEM';
export const LOAD_CART_LOCAL_DATA = 'LOAD_CART_LOCAL_DATA';
export const CLEAR_CART_DATA = 'CLEAR_CART_DATA';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const UPDATE_QUANTITY_ITEM = 'UPDATE_QUANTITY_ITEM';

export const UPDATE_CURRENT_USER_DATA = 'UPDATE_USER_DATA';
export const CLEAR_CURRENT_USER_DATA = 'CLEAR_USER_DATA';

export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
